"""init

Revision ID: 9494ba92a784
Revises: 
Create Date: 2025-01-29 12:22:39.825006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9494ba92a784'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meets_id'), 'meets', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('task_manager_id', sa.Integer(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='grade'), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_participants',
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('meet_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meet_participants')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_meets_id'), table_name='meets')
    op.drop_table('meets')
    # ### end Alembic commands ###
