"""Edit models 3

Revision ID: 9c7ee6f81dff
Revises: 04259e73f43a
Create Date: 2025-01-27 22:23:38.642193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7ee6f81dff'
down_revision: Union[str, None] = '04259e73f43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_invite_code', table_name='companies')
    op.drop_column('companies', 'invite_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('invite_code', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_index('ix_companies_invite_code', 'companies', ['invite_code'], unique=True)
    # ### end Alembic commands ###
