"""Edit models

Revision ID: e93170744c45
Revises: 629f10dd3f76
Create Date: 2025-01-27 22:14:06.044015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93170744c45'
down_revision: Union[str, None] = '629f10dd3f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    op.add_column('companies', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['admin_id'], ['id'])
    op.add_column('departments', sa.Column('department_head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['department_head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'department_head_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'admin_id')
    op.drop_table('department_admins')
    # ### end Alembic commands ###
